fix WSL bug: url hash params cut-off (closes #20)
tpapp/DefaultApplication.jl pull request #21
Opened 2023-01-28 14:03 UTC by tfiers

Re
- https://github.com/tpapp/DefaultApplication.jl/issues/20

This PR checks whether the `filename` is an existing file or directory, and only then `relpath`s it

2023-01-28 14:05 UTC, tfiers commented
Re @cjdoris: I edited your code with a check. Ok for you too?

2023-01-28 18:15 UTC, tfiers commented
Updated this branch to also fix
- #22

2023-01-28 18:32 UTC, tfiers commented
Tested manually, on both WSL and Windows, using:
```
julia> using DefaultApplication

julia> link = "https://google.com/#" * ("x"^8200);

julia> DefaultApplication.open(link);

julia>  DefaultApplication.open("README.md");
```
..which all works now

2023-01-29 16:43 UTC, tpapp requested changes
Thanks for the nice work, I asked for some minor changes.

Setting up CI for Windows is not a precondition for merging this PR, but it would be nice.

2023-01-29 16:43 UTC, tpapp commented on src/DefaultApplication.jl
> +        if _win__cmd_is_too_long(cmd)
Since this is used in one place, it does not warrant a separate function. Just evaluate the length directly here and add the comment from below.

2023-01-29 16:43 UTC, tpapp commented on src/DefaultApplication.jl
> +_powershell_start_cmd(path) = `powershell.exe -NoProfile -NonInteractive -Command start \"$(path)\"`
Please use `function ... end`, add a docstring, and put the comment in the body.

2023-01-29 16:43 UTC, tpapp commented on test/windows.jl
> +# Not run automatically, yet
please make them run automatically

2023-01-30 00:21 UTC, tfiers commented
Thank you for the review.

For the testing, what do you think about factoring `open` into two functions, with one returning the `Cmd` objects, and the other actually `run`ning them.
That way, testing is easier

2023-01-30 09:27 UTC, tpapp commented
Great idea, please do it.

2023-02-09 00:32 UTC, tfiers commented
Voila, all the above done.
Let's test if the new CI works

2023-02-09 07:13 UTC, tfiers commented
Ok I ran the actions on my own branch. After the last two commits they run succesfully now, down to 1.0: https://github.com/tfiers/DefaultApplication.jl/actions/runs/4131800096

(Cloning the registry, in the buildpkg step, makes the windows and macos runs slow; this could be cached I suppose)

2023-02-09 08:41 UTC, tpapp approved these changes
LGTM, thanks!

2023-02-09 08:43 UTC, merged